### ISSUE TITLE
Обновление баз даних

### ISSUE THREAD

**Issue by morda1983** [borodulin/wotdb#10]
﻿PHP Error[8]: Undefined index: achievements
    in file /home/admin/web/stat2.ki-eb.pp.ua/public_html/protected/components/WotService.php at line 382
#0 /home/admin/web/stat2.ki-eb.pp.ua/public_html/protected/components/WotService.php(353): updateClanPlayersInfo()
#1 /home/admin/web/stat2.ki-eb.pp.ua/public_html/protected/commands/CronCommand.php(12): scanClan()
#2 unknown(0): CronCommand->actionScan()
#3 /home/admin/web/stat2.ki-eb.pp.ua/public_html/protected/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs()
#4 /home/admin/web/stat2.ki-eb.pp.ua/public_html/protected/framework/console/CConsoleCommandRunner.php(71): CronCommand->run()
#5 /home/admin/web/stat2.ki-eb.pp.ua/public_html/protected/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run()
#6 /home/admin/web/stat2.ki-eb.pp.ua/public_html/protected/framework/base/CApplication.php(180): CConsoleApplication->processRequest()
#7 /home/admin/web/stat2.ki-eb.pp.ua/public_html/protected/framework/yiic.php(33): CConsoleApplication->run()
#8 /home/admin/web/stat2.ki-eb.pp.ua/public_html/protected/yiic.php(7): require_once()
#9 /home/admin/web/stat2.ki-eb.pp.ua/public_html/protected/yiic(4): require_once()

**Comment by borodulin** [comment]
пофиксил
