### ISSUE TITLE
Посещение укрепрайонов

### ISSUE THREAD

**Issue by morda1983** [borodulin/wotdb#11]
Возможно ли добавить страницу с посещением укрепов, вылазок защиты и атаки.

**Comment by borodulin** [comment]
Тут много чего возможно, но я в танки уже месяц наверное не играл. Могу добавить в проект, если интересно - развивайте. Могу только советом помочь. Со временем сейчас туго, не до альтруистических проектов.

**Comment by morda1983** [comment]
Я не програмист, и учится сейчас времени нету тоже, так играю в день только 2-3 боя и то на гк. СПС за ответ.
